In [1]:
import os
import re
import random
from pathlib import Path
import json
import pandas as pd

In [2]:
# working directory for relative paths
notebooks_path = Path.cwd() # <repo-root>/noteboooks
repo_root_path = notebooks_path.parent # <repo-root>/
data_path = repo_root_path / "data" # <repo-root>/data
input_dataset_path = data_path / "anom_get_urls_counts.csv" # input: anom_get_urls_counts

In [3]:
anom_only_urls_file = repo_root_path / "data" / "anom_only_urls.paraquet"


anom_only_urls_df = pd.read_parquet(anom_only_urls_file)
print(f"loaded: {anom_only_urls_file}")
print(f"shape: {anom_only_urls_df.shape}")

loaded: /mnt/hgfs/workspace/mlhttp/data/anom_only_urls.paraquet
shape: (1615, 2)

In [4]:
anom_only_urls_df.head(30)

label                                          anom  norm
url
http://localhost:8080.BAK                        19     0
http://localhost:8080.Bak                        20     0
http://localhost:8080.INC                        13     0
http://localhost:8080.Inc                        25     0
http://localhost:8080.OLD                        20     0
http://localhost:8080.Old                        22     0
http://localhost:8080.bak                        23     0
http://localhost:8080.inc                        16     0
http://localhost:8080.java                       16     0
http://localhost:8080.old                        27     0
http://localhost:8080/                           51     0
http://localhost:8080/.BAK                        6     0
http://localhost:8080/.Bak                        1     0
http://localhost:8080/.INC                        6     0
http://localhost:8080/.Inc                        5     0
http://localhost:8080/.OLD                        4     0
http://localhost:8080/.Old                        6     0
http://localhost:8080/.bak                        2     0
http://localhost:8080/.inc                        1     0
http://localhost:8080/.java                       1     0
http://localhost:8080/.jsp                       10     0
http://localhost:8080/.old                        2     0
http://localhost:8080/4861362529278789730        36     0
http://localhost:8080/4861362529278789730.BAK     2     0
http://localhost:8080/4861362529278789730.Bak     3     0
http://localhost:8080/4861362529278789730.INC     2     0
http://localhost:8080/4861362529278789730.Inc     2     0
http://localhost:8080/4861362529278789730.OLD     4     0
http://localhost:8080/4861362529278789730.Old     2     0
http://localhost:8080/4861362529278789730.bak     4     0

**Observations:**  

Multiple Malformed short URLs variations:  
- With similar extensions `.BAK, .Bak, .bak` `.INC`, `.Inc`, `.inc` `.OLD`, `.Old`, `.old`, `java`, `.jsp`
- Cases where urls `http://localhost:8080` followed by
    -  (**No** `/`) direct `.` and extension
    -  `/` only
    -  `/` with `.` and extension
    - `/` and large numeric value
    - `/` and large numeric value and extension

Group these into two pattern families - 
- first three: (`/` or `.` or `/.`) and (<`extension`>)
- next two: <`large-numeric-id`>

In [5]:

# families = {
#     "outside_app":    ~anom_only_urls.str.startswith("http://localhost:8080/tienda1/"),
#     "backup_ext":      anom_only_urls.str.contains(r"\.(?:bak|old|inc|java)(?:\.|$)|~$|~\.", case=False, regex=True),
#     "numeric_id":     anom_only_urls.str.contains(r"\d{10,}"),
#     "asf_probe":      anom_only_urls.str.contains("asf-logo-wide", case=False),
#     "trailing_slash":      (anom_only_urls.str.endswith("/") & ~anom_only_urls.str.endswith("tienda1/")),
# }

Start with full set

In [6]:
# Original Dataset
anom_only_remaining_df = anom_only_urls_df
anom_only_remaining_df.shape

(1615, 2)

Define the pattern management and URL filtering utilities

In [7]:
# Pattern-family registry
pattern_families = {}

def new_pattern_family(family: str):
    """Create an empty pattern family (list of regex alternatives)."""
    pattern_families[family] = []


def extend_pattern(family: str, *patterns: str):
    """Add one or more regex alternatives to an existing family."""
    if family not in pattern_families:
        raise KeyError(f"family '{family}' not created — call new_pattern_family first")
    pattern_families[family].extend(patterns)   # extend - flat list of strings

def overwrite_pattern(family: str, *patterns: str):
    """Overwrite one or more regex alternatives to an existing family."""
    if family not in pattern_families:
        raise KeyError(f"family '{family}' not created — call new_pattern_family first")
     # Overwrite new given patterns
    pattern_families[family] = []
    pattern_families[family].extend(patterns)

# Pattern Compile
def compiled_pattern(families: dict) -> dict:
    """Join each family's alternatives into one regex string."""
    compiled = {name: "|".join(pats) for name, pats in families.items()}
    print(f"compiled_pattern: {compiled}")
    return compiled

# Filter dataset on compiled urls
def filter_urls(df_input, compiled):
    #urls = df_input.index.to_series()
    df_remaining = df_input
    for name, pat in compiled.items():
        print(f"{name}: {pat}")
        urls = df_remaining.index.to_series() 
        suffix_mask = urls.str.contains(pat, case=False, regex=True, na=False)

        
        df_suffix = df_remaining.loc[suffix_mask].copy()
        df_remaining = df_remaining.loc[~suffix_mask].copy()
        
        print(f"{name}_suffix URLs: {len(df_suffix)} URLs, {df_suffix['anom'].sum()} requests")
        print(f"remaining URLs:   {len(df_remaining)} URLs, {df_remaining['anom'].sum()} requests")
        print("-" * 80)
    return df_remaining

In [8]:
# extension followed pattern 
extension_pattern= r"\.(?:bak|old|inc|java|jsp)" 
numeric_id_pattern=(r"\d{10,}")

# Define a new extensions family and add pattern
new_pattern_family("extensions")
extend_pattern("extensions", extension_pattern)

# Define a new numeric-id family and add pattern
new_pattern_family("numeric-id")
extend_pattern("numeric-id", numeric_id_pattern)

# Compile the pattern
compiled = compiled_pattern(pattern_families)

# Filter URLs on compiled patterns
anom_only_remaining_df = filter_urls(anom_only_remaining_df, compiled)

compiled_pattern: {'extensions': '\\.(?:bak|old|inc|java|jsp)', 'numeric-id': '\\d{10,}'}
extensions: \.(?:bak|old|inc|java|jsp)
extensions_suffix URLs: 1308 URLs, 3398 requests
remaining URLs:   307 URLs, 2110 requests
--------------------------------------------------------------------------------
numeric-id: \d{10,}
numeric-id_suffix URLs: 26 URLs, 174 requests
remaining URLs:   281 URLs, 1936 requests
--------------------------------------------------------------------------------

In [9]:
print(f"Dataframe shape: {anom_only_remaining_df.shape}")
print(f"pattern_families:\n{json.dumps(pattern_families, indent=2)}")

Dataframe shape: (281, 2)
pattern_families:
{
  "extensions": [
    "\\.(?:bak|old|inc|java|jsp)"
  ],
  "numeric-id": [
    "\\d{10,}"
  ]
}

Sample next batch of URLs for analysis from the filtered dataset

In [10]:
anom_only_remaining_df.head(30)

label                                               anom  norm
url
http://localhost:8080/                                51     0
http://localhost:8080/CFIDE/administrator/Appli...     5     0
http://localhost:8080/CFIDE/administrator/about...     7     0
http://localhost:8080/CFIDE/administrator/check...     6     0
http://localhost:8080/CFIDE/administrator/enter...     9     0
http://localhost:8080/CFIDE/administrator/heade...     9     0
http://localhost:8080/CFIDE/administrator/homef...     4     0
http://localhost:8080/CFIDE/administrator/homep...     8     0
http://localhost:8080/CFIDE/administrator/index...     9     0
http://localhost:8080/CFIDE/administrator/left.cfm    10     0
http://localhost:8080/CFIDE/administrator/linkd...     3     0
http://localhost:8080/CFIDE/administrator/login...    11     0
http://localhost:8080/CFIDE/administrator/logou...    11     0
http://localhost:8080/CFIDE/administrator/navse...     6     0
http://localhost:8080/CFIDE/administrator/right...     2     0
http://localhost:8080/CFIDE/administrator/tabs.cfm     2     0
http://localhost:8080/CFIDE/administrator/welco...     4     0
http://localhost:8080/CFIDE/administrator/welco...     6     0
http://localhost:8080/CFIDE/administrator/welco...    10     0
http://localhost:8080/CFIDE/administrator/welco...     9     0
http://localhost:8080/CFIDE/administrator/welco...     5     0
http://localhost:8080/IBMWebAS                        11     0
http://localhost:8080/IISSamples/sdk/asp/applic...     5     0
http://localhost:8080/IISSamples/sdk/asp/applic...     9     0
http://localhost:8080/IISSamples/sdk/asp/applic...     5     0
http://localhost:8080/IISSamples/sdk/asp/applic...     4     0
http://localhost:8080/IISSamples/sdk/asp/databa...     5     0
http://localhost:8080/IISSamples/sdk/asp/databa...     8     0
http://localhost:8080/IISSamples/sdk/asp/databa...     8     0
http://localhost:8080/IISSamples/sdk/asp/databa...    11     0

**Observations:**  

Multiple Malformed URLs variations:  
- Trailing slash `http://localhost:8080/` 	
- Adobe coldfusion scan probes - URLs with `CFIDE/...`
- IBM WebSphere scan probes - URLs with (`IBMWebAS`)
- MS IIS server scan probes - URLs with (`IISSamples/...`)

Group each one into its own respective pattern family

In [11]:

# families = {
#     "outside_app":    ~anom_only_urls.str.startswith("http://localhost:8080/tienda1/"),
#     "backup_ext":      anom_only_urls.str.contains(r"\.(?:bak|old|inc|java)(?:\.|$)|~$|~\.", case=False, regex=True),
#     "numeric_id":     anom_only_urls.str.contains(r"\d{10,}"),
#     "asf_probe":      anom_only_urls.str.contains("asf-logo-wide", case=False),
#     "trailing_slash":      (anom_only_urls.str.endswith("/") & ~anom_only_urls.str.endswith("tienda1/")),
# }

In [12]:
# Define the patterns
trailing_slash_pattern = (r"^https?://[^/:]+:\d{1,5}/$")
adobe_coldfusion_patterns = (r"CFIDE/")
websphere_patterns = (r"IBMWebAS")
iis_patterns = (r"IISSamples")

# Define a new trailing_slash family and add pattern
new_pattern_family("trailing_slash")
extend_pattern("trailing_slash", trailing_slash_pattern)

# Define a new adobe coldfusion family and add pattern
new_pattern_family("adobe_coldfusion")
extend_pattern("adobe_coldfusion", adobe_coldfusion_patterns)

# Define a new websphere family and add pattern
new_pattern_family("websphere")
extend_pattern("websphere", websphere_patterns)

# Define a new websphere family and add pattern
new_pattern_family("iis")
extend_pattern("iis", iis_patterns)

# Compile the pattern
compiled = compiled_pattern(pattern_families)

# Reset to original Dataset
anom_only_remaining_df = anom_only_urls_df
print(anom_only_remaining_df.shape)

# Filter URLs on compiled patterns
anom_only_remaining_df = filter_urls(anom_only_remaining_df, compiled)

compiled_pattern: {'extensions': '\\.(?:bak|old|inc|java|jsp)', 'numeric-id': '\\d{10,}', 'trailing_slash': '^https?://[^/:]+:\\d{1,5}/$', 'adobe_coldfusion': 'CFIDE/', 'websphere': 'IBMWebAS', 'iis': 'IISSamples'}
(1615, 2)
extensions: \.(?:bak|old|inc|java|jsp)
extensions_suffix URLs: 1308 URLs, 3398 requests
remaining URLs:   307 URLs, 2110 requests
--------------------------------------------------------------------------------
numeric-id: \d{10,}
numeric-id_suffix URLs: 26 URLs, 174 requests
remaining URLs:   281 URLs, 1936 requests
--------------------------------------------------------------------------------
trailing_slash: ^https?://[^/:]+:\d{1,5}/$
trailing_slash_suffix URLs: 1 URLs, 51 requests
remaining URLs:   280 URLs, 1885 requests
--------------------------------------------------------------------------------
adobe_coldfusion: CFIDE/
adobe_coldfusion_suffix URLs: 20 URLs, 136 requests
remaining URLs:   260 URLs, 1749 requests
--------------------------------------------------------------------------------
websphere: IBMWebAS
websphere_suffix URLs: 1 URLs, 11 requests
remaining URLs:   259 URLs, 1738 requests
--------------------------------------------------------------------------------
iis: IISSamples
iis_suffix URLs: 21 URLs, 157 requests
remaining URLs:   238 URLs, 1581 requests
--------------------------------------------------------------------------------

In [13]:
print(f"Dataframe shape: {anom_only_remaining_df.shape}")
print(f"pattern_families:\n{json.dumps(pattern_families, indent=2)}")

Dataframe shape: (238, 2)
pattern_families:
{
  "extensions": [
    "\\.(?:bak|old|inc|java|jsp)"
  ],
  "numeric-id": [
    "\\d{10,}"
  ],
  "trailing_slash": [
    "^https?://[^/:]+:\\d{1,5}/$"
  ],
  "adobe_coldfusion": [
    "CFIDE/"
  ],
  "websphere": [
    "IBMWebAS"
  ],
  "iis": [
    "IISSamples"
  ]
}

Sample next batch of URLs for analysis from the filtered dataset

In [14]:
anom_only_remaining_df.head(30)

label                                               anom  norm
url
http://localhost:8080/SmarTicketApp/index.html         6     0
http://localhost:8080/WEB-INF/web.xml                  4     0
http://localhost:8080/WEB-INF/webapp.properties        3     0
http://localhost:8080/WebSphereSamples/               23     0
http://localhost:8080/WebSphereSamples/SingleSa...     8     0
http://localhost:8080/WebSphereSamples/SingleSa...    11     0
http://localhost:8080/WebSphereSamples/YourCo/m...     5     0
http://localhost:8080/_cti_pvt/access.cnf              3     0
http://localhost:8080/_cti_pvt/botinfs.cnf             8     0
http://localhost:8080/_cti_pvt/bots.cnf                7     0
http://localhost:8080/_cti_pvt/dectodep.btr            9     0
http://localhost:8080/_cti_pvt/deptodoc.btr            8     0
http://localhost:8080/_cti_pvt/linkinfo.cnf           10     0
http://localhost:8080/_cti_pvt/service.cnf             5     0
http://localhost:8080/_cti_pvt/services.cnf            4     0
http://localhost:8080/_cti_pvt/svcacl.cnf              6     0
http://localhost:8080/_cti_pvt/uniqperm.cnf            6     0
http://localhost:8080/_cti_pvt/writeto.cnf             5     0
http://localhost:8080/_private/                        9     0
http://localhost:8080/_vti_bin/                       18     0
http://localhost:8080/_vti_bin/_vti_adm/admin.dll      6     0
http://localhost:8080/_vti_bin/_vti_aut/author.dll     6     0
http://localhost:8080/_vti_bin/fpcount.exe             6     0
http://localhost:8080/_vti_bin/shtml.dll               6     0
http://localhost:8080/_vti_cnf/                       12     0
http://localhost:8080/_vti_inf.html                    4     0
http://localhost:8080/_vti_log/                       15     0
http://localhost:8080/_vti_pvt/                       13     0
http://localhost:8080/_vti_script/                    13     0
http://localhost:8080/_vti_txt/                        2     0

**Observations:**  

Multiple Malformed URLs variations:  
- More variations of IBM WebSphere scan probes - URLs with (`webapp...`, `WebSphere...`, `SmarTicketApp...`)
- Microsoft frontpage scan probes - URLs with (`_cti...`, `_private...`, `_vti...`)
- Java metadata probes - URLs with `WEB-INF`

Extend the websphere pattern family and make new one for ms frontpage and Java app

In [15]:
# Define the patterns
more_websphere_patterns = (r"webapp|WebSphere|SmarTicketApp")
frontpage_patterns = (r"_cti|_private|_vti")
java_patterns = (r"WEB-INF")

# Extend a websphere family patterns
extend_pattern("websphere", more_websphere_patterns)

# Define a new frontpage family and add pattern
new_pattern_family("frontpage")
extend_pattern("frontpage", frontpage_patterns)

# Define a new java family and add pattern
new_pattern_family("java")
extend_pattern("java", java_patterns)

# Compile the pattern
compiled = compiled_pattern(pattern_families)

# Reset to original Dataset
anom_only_remaining_df = anom_only_urls_df
print(anom_only_remaining_df.shape)

# Filter URLs on compiled patterns
anom_only_remaining_df = filter_urls(anom_only_remaining_df, compiled)

compiled_pattern: {'extensions': '\\.(?:bak|old|inc|java|jsp)', 'numeric-id': '\\d{10,}', 'trailing_slash': '^https?://[^/:]+:\\d{1,5}/$', 'adobe_coldfusion': 'CFIDE/', 'websphere': 'IBMWebAS|webapp|WebSphere|SmarTicketApp', 'iis': 'IISSamples', 'frontpage': '_cti|_private|_vti', 'java': 'WEB-INF'}
(1615, 2)
extensions: \.(?:bak|old|inc|java|jsp)
extensions_suffix URLs: 1308 URLs, 3398 requests
remaining URLs:   307 URLs, 2110 requests
--------------------------------------------------------------------------------
numeric-id: \d{10,}
numeric-id_suffix URLs: 26 URLs, 174 requests
remaining URLs:   281 URLs, 1936 requests
--------------------------------------------------------------------------------
trailing_slash: ^https?://[^/:]+:\d{1,5}/$
trailing_slash_suffix URLs: 1 URLs, 51 requests
remaining URLs:   280 URLs, 1885 requests
--------------------------------------------------------------------------------
adobe_coldfusion: CFIDE/
adobe_coldfusion_suffix URLs: 20 URLs, 136 requests
remaining URLs:   260 URLs, 1749 requests
--------------------------------------------------------------------------------
websphere: IBMWebAS|webapp|WebSphere|SmarTicketApp
websphere_suffix URLs: 15 URLs, 136 requests
remaining URLs:   245 URLs, 1613 requests
--------------------------------------------------------------------------------
iis: IISSamples
iis_suffix URLs: 21 URLs, 157 requests
remaining URLs:   224 URLs, 1456 requests
--------------------------------------------------------------------------------
frontpage: _cti|_private|_vti
frontpage_suffix URLs: 23 URLs, 181 requests
remaining URLs:   201 URLs, 1275 requests
--------------------------------------------------------------------------------
java: WEB-INF
java_suffix URLs: 1 URLs, 4 requests
remaining URLs:   200 URLs, 1271 requests
--------------------------------------------------------------------------------

In [16]:
print(f"Dataframe shape: {anom_only_remaining_df.shape}")
print(f"pattern_families:\n{json.dumps(pattern_families, indent=2)}")
bk_pattern_families = pattern_families

Dataframe shape: (200, 2)
pattern_families:
{
  "extensions": [
    "\\.(?:bak|old|inc|java|jsp)"
  ],
  "numeric-id": [
    "\\d{10,}"
  ],
  "trailing_slash": [
    "^https?://[^/:]+:\\d{1,5}/$"
  ],
  "adobe_coldfusion": [
    "CFIDE/"
  ],
  "websphere": [
    "IBMWebAS",
    "webapp|WebSphere|SmarTicketApp"
  ],
  "iis": [
    "IISSamples"
  ],
  "frontpage": [
    "_cti|_private|_vti"
  ],
  "java": [
    "WEB-INF"
  ]
}

In [17]:
pattern_families = bk_pattern_families
print(f"pattern_families:\n{json.dumps(pattern_families, indent=2)}")

pattern_families:
{
  "extensions": [
    "\\.(?:bak|old|inc|java|jsp)"
  ],
  "numeric-id": [
    "\\d{10,}"
  ],
  "trailing_slash": [
    "^https?://[^/:]+:\\d{1,5}/$"
  ],
  "adobe_coldfusion": [
    "CFIDE/"
  ],
  "websphere": [
    "IBMWebAS",
    "webapp|WebSphere|SmarTicketApp"
  ],
  "iis": [
    "IISSamples"
  ],
  "frontpage": [
    "_cti|_private|_vti"
  ],
  "java": [
    "WEB-INF"
  ]
}

Sample next batch of URLs for analysis from the filtered dataset

In [18]:
anom_only_remaining_df.head(30)

label                                               anom  norm
url
http://localhost:8080/admin.nsf                        7     0
http://localhost:8080/admin/login.do                   8     0
http://localhost:8080/admin4.nsf                      11     0
http://localhost:8080/admin5.nsf                       9     0
http://localhost:8080/agentrunner.nsf                  4     0
http://localhost:8080/alog.nsf                         6     0
http://localhost:8080/asf-logo-wide                   39     0
http://localhost:8080/asf-logo-wide.gif               37     0
http://localhost:8080/asf-logo-wide.gif/              38     0
http://localhost:8080/asf-logo-wide.gif/~              5     0
http://localhost:8080/asf-logo-wide.gif~               7     0
http://localhost:8080/asf-logo-wide~                   5     0
http://localhost:8080/bookmarks.nsf                    5     0
http://localhost:8080/busytime.nsf                     6     0
http://localhost:8080/catalog.nsf                      7     0
http://localhost:8080/certsrv.nsf                      5     0
http://localhost:8080/databasenotes.html               4     0
http://localhost:8080/dspug.nsf                        7     0
http://localhost:8080/e2ePortalProject/Login.po...     4     0
http://localhost:8080/estore/annotated-index.html      4     0
http://localhost:8080/estore/index.html                3     0
http://localhost:8080/estore/populate                  6     0
http://localhost:8080/events4.nsf                     10     0
http://localhost:8080/flash/java/javabean/Flash...     7     0
http://localhost:8080/homepage.nsf                     8     0
http://localhost:8080/iisadmin/htmldocs/iisdocs...     6     0
http://localhost:8080/iisadmpwd/achg.htr              10     0
http://localhost:8080/iisadmpwd/aexp.htr               5     0
http://localhost:8080/iisadmpwd/aexp2.htr             11     0
http://localhost:8080/iisadmpwd/aexp2b.htr            10     0

**Observations:**  

Multiple Malformed URLs variations: 
- Lotus Domino databases probes - - URLs with (`.nsf`)
- Apache Software Foundation probes - - URLs with (`asf-logo...`)
- More variations of IIS server scan probes - URLs with (`iisadmin...`, `iisadmpwd`)
- More variations of IBM WebSphere/J2EE scan probes - URLs with (`estore...`)
- WebLogic Portal probes - URLs with (`e2ePortalProject...`)
- Apache Struts application probe - URLs with (`admin/login.do`)
- Allaire/Macromedia JRun application probe - URLs with (`flash/java/javabean/FlashJavaBean...`)
- Known scanner wordlist probe - URLs with `databasenotes...`

In [19]:
# Define the patterns
lotus_domino_patterns = (r"\.nsf$")
asf_patterns = (r"asf-logo-wide")
more_iis_patterns = (r"iisadmin|iisadmpwd")
more_websphere_patterns = (r"estore")
portal_app_pattern = (r"e2ePortalProject")
# #more_java_patterns = (r"\.do$", r"flash/java/javabean|FlashJavaBean")
more_java_patterns = (r"\.do$|flash/java/javabean|FlashJavaBean")
file_patterns = (r"databasenotes\.html")

# Define a new lotus domino family and add pattern
new_pattern_family("lotus_domino")
extend_pattern("lotus_domino", lotus_domino_patterns)

# Define a new ASF family and add pattern
new_pattern_family("asf")
extend_pattern("asf", asf_patterns)

# Extend a IIS family patterns
extend_pattern("iis", more_iis_patterns)

# Extend a websphere family patterns
extend_pattern("websphere", more_websphere_patterns)

# Define a new frontpage family and add pattern
new_pattern_family("portal_app")
extend_pattern("portal_app", portal_app_pattern)

# Define a new java family and add pattern
extend_pattern("java", more_java_patterns)

# # Define a new file family and add pattern
new_pattern_family("file")
extend_pattern("file", file_patterns)

# Compile the pattern
compiled = compiled_pattern(pattern_families)

# Reset to original Dataset
anom_only_remaining_df = anom_only_urls_df
print(anom_only_remaining_df.shape)

# Filter URLs on compiled patterns
anom_only_remaining_df = filter_urls(anom_only_remaining_df, compiled)

compiled_pattern: {'extensions': '\\.(?:bak|old|inc|java|jsp)', 'numeric-id': '\\d{10,}', 'trailing_slash': '^https?://[^/:]+:\\d{1,5}/$', 'adobe_coldfusion': 'CFIDE/', 'websphere': 'IBMWebAS|webapp|WebSphere|SmarTicketApp|estore', 'iis': 'IISSamples|iisadmin|iisadmpwd', 'frontpage': '_cti|_private|_vti', 'java': 'WEB-INF|\\.do$|flash/java/javabean|FlashJavaBean', 'lotus_domino': '\\.nsf$', 'asf': 'asf-logo-wide', 'portal_app': 'e2ePortalProject', 'file': 'databasenotes\\.html'}
(1615, 2)
extensions: \.(?:bak|old|inc|java|jsp)
extensions_suffix URLs: 1308 URLs, 3398 requests
remaining URLs:   307 URLs, 2110 requests
--------------------------------------------------------------------------------
numeric-id: \d{10,}
numeric-id_suffix URLs: 26 URLs, 174 requests
remaining URLs:   281 URLs, 1936 requests
--------------------------------------------------------------------------------
trailing_slash: ^https?://[^/:]+:\d{1,5}/$
trailing_slash_suffix URLs: 1 URLs, 51 requests
remaining URLs:   280 URLs, 1885 requests
--------------------------------------------------------------------------------
adobe_coldfusion: CFIDE/
adobe_coldfusion_suffix URLs: 20 URLs, 136 requests
remaining URLs:   260 URLs, 1749 requests
--------------------------------------------------------------------------------
websphere: IBMWebAS|webapp|WebSphere|SmarTicketApp|estore
websphere_suffix URLs: 18 URLs, 149 requests
remaining URLs:   242 URLs, 1600 requests
--------------------------------------------------------------------------------
iis: IISSamples|iisadmin|iisadmpwd
iis_suffix URLs: 30 URLs, 222 requests
remaining URLs:   212 URLs, 1378 requests
--------------------------------------------------------------------------------
frontpage: _cti|_private|_vti
frontpage_suffix URLs: 23 URLs, 181 requests
remaining URLs:   189 URLs, 1197 requests
--------------------------------------------------------------------------------
java: WEB-INF|\.do$|flash/java/javabean|FlashJavaBean
java_suffix URLs: 6 URLs, 41 requests
remaining URLs:   183 URLs, 1156 requests
--------------------------------------------------------------------------------
lotus_domino: \.nsf$
lotus_domino_suffix URLs: 18 URLs, 128 requests
remaining URLs:   165 URLs, 1028 requests
--------------------------------------------------------------------------------
asf: asf-logo-wide
asf_suffix URLs: 72 URLs, 529 requests
remaining URLs:   93 URLs, 499 requests
--------------------------------------------------------------------------------
portal_app: e2ePortalProject
portal_app_suffix URLs: 1 URLs, 4 requests
remaining URLs:   92 URLs, 495 requests
--------------------------------------------------------------------------------
file: databasenotes\.html
file_suffix URLs: 1 URLs, 4 requests
remaining URLs:   91 URLs, 491 requests
--------------------------------------------------------------------------------

In [20]:
print(f"Dataframe shape: {anom_only_remaining_df.shape}")
print(f"pattern_families:\n{json.dumps(pattern_families, indent=2)}")

Dataframe shape: (91, 2)
pattern_families:
{
  "extensions": [
    "\\.(?:bak|old|inc|java|jsp)"
  ],
  "numeric-id": [
    "\\d{10,}"
  ],
  "trailing_slash": [
    "^https?://[^/:]+:\\d{1,5}/$"
  ],
  "adobe_coldfusion": [
    "CFIDE/"
  ],
  "websphere": [
    "IBMWebAS",
    "webapp|WebSphere|SmarTicketApp",
    "estore"
  ],
  "iis": [
    "IISSamples",
    "iisadmin|iisadmpwd"
  ],
  "frontpage": [
    "_cti|_private|_vti"
  ],
  "java": [
    "WEB-INF",
    "\\.do$|flash/java/javabean|FlashJavaBean"
  ],
  "lotus_domino": [
    "\\.nsf$"
  ],
  "asf": [
    "asf-logo-wide"
  ],
  "portal_app": [
    "e2ePortalProject"
  ],
  "file": [
    "databasenotes\\.html"
  ]
}

Sample next batch of URLs for analysis from the filtered dataset

In [21]:
anom_only_remaining_df.head(30)

label                                               anom  norm
url
http://localhost:8080/iisstart.asp                     4     0
http://localhost:8080/iisstart.htm                     9     0
http://localhost:8080/jstl-war/index.html              9     0
http://localhost:8080/mail.box                         6     0
http://localhost:8080/msadc/msadcs.dll                16     0
http://localhost:8080/msadc/readme.txt                 2     0
http://localhost:8080/msadc/samples/adctest.asp        6     0
http://localhost:8080/msadc/samples/selector/sh...     8     0
http://localhost:8080/postinfo.html                    5     0
http://localhost:8080/samples/dbsamp/dbsamp.htm        6     0
http://localhost:8080/samples/dbsamp/dbsamp1.htm       8     0
http://localhost:8080/samples/dbsamp/dbsamp2.htm       5     0
http://localhost:8080/samples/dbsamp/dbsamp3.htm       6     0
http://localhost:8080/samples/gbook/query.htm          5     0
http://localhost:8080/samples/gbook/register.htm       5     0
http://localhost:8080/samples/htmlsamp/htmlsamp...     6     0
http://localhost:8080/samples/htmlsamp/styles.htm      3     0
http://localhost:8080/samples/htmlsamp/styles2.htm     5     0
http://localhost:8080/samples/htmlsamp/tables.htm      7     0
http://localhost:8080/samples/isapi/drop.htm           5     0
http://localhost:8080/samples/isapi/favlist.htm        5     0
http://localhost:8080/samples/isapi/isapi.htm          9     0
http://localhost:8080/samples/isapi/srch.htm           2     0
http://localhost:8080/samples/sampsite/about.htm       4     0
http://localhost:8080/samples/sampsite/catalog.htm     9     0
http://localhost:8080/samples/sampsite/dfault.htm      3     0
http://localhost:8080/samples/sampsite/process.htm     4     0
http://localhost:8080/samples/sampsite/results.htm    10     0
http://localhost:8080/samples/sampsite/sampsite...     7     0
http://localhost:8080/samples/sampsite/sendme.htm      6     0

**Observations:**  

Multiple Malformed URLs variations: 
- More variations of IIS scan probes - URLs with (`iisstart...`, `msadc...`, `samples...`)
- More variations Java metadata probes - URLs with `jstl-war...`
- More Lotus Domino databases probes - - URLs with (`mail.box`)
- More Microsoft frontpage scan probes - URLs with (`postinfo...`)

In [22]:
# Define the patterns
more_iis_patterns = (r"iisstart|msadc")
some_more_iis_patterns = (r"/samples/(?:dbsamp|gbook|htmlsamp|isapi|sampsite)/")
more_java_patterns = (r"jstl-war")
more_lotus_domino_patterns = (r"/mail\.box$")
more_frontpage_patterns = (r"postinfo\.html")

# Add more IIS family patterns
extend_pattern("iis", more_iis_patterns)
extend_pattern("iis", some_more_iis_patterns)

# Add more Java family patterns
extend_pattern("java", more_java_patterns)

# Add more  domino family patterns
extend_pattern("lotus_domino", more_lotus_domino_patterns)

# Add more frontpage family patterns
extend_pattern("frontpage", more_frontpage_patterns)

# Compile the pattern
compiled = compiled_pattern(pattern_families)

# Reset to original Dataset
anom_only_remaining_df = anom_only_urls_df
print(anom_only_remaining_df.shape)

# Filter URLs on compiled patterns
anom_only_remaining_df = filter_urls(anom_only_remaining_df, compiled)

compiled_pattern: {'extensions': '\\.(?:bak|old|inc|java|jsp)', 'numeric-id': '\\d{10,}', 'trailing_slash': '^https?://[^/:]+:\\d{1,5}/$', 'adobe_coldfusion': 'CFIDE/', 'websphere': 'IBMWebAS|webapp|WebSphere|SmarTicketApp|estore', 'iis': 'IISSamples|iisadmin|iisadmpwd|iisstart|msadc|/samples/(?:dbsamp|gbook|htmlsamp|isapi|sampsite)/', 'frontpage': '_cti|_private|_vti|postinfo\\.html', 'java': 'WEB-INF|\\.do$|flash/java/javabean|FlashJavaBean|jstl-war', 'lotus_domino': '\\.nsf$|/mail\\.box$', 'asf': 'asf-logo-wide', 'portal_app': 'e2ePortalProject', 'file': 'databasenotes\\.html'}
(1615, 2)
extensions: \.(?:bak|old|inc|java|jsp)
extensions_suffix URLs: 1308 URLs, 3398 requests
remaining URLs:   307 URLs, 2110 requests
--------------------------------------------------------------------------------
numeric-id: \d{10,}
numeric-id_suffix URLs: 26 URLs, 174 requests
remaining URLs:   281 URLs, 1936 requests
--------------------------------------------------------------------------------
trailing_slash: ^https?://[^/:]+:\d{1,5}/$
trailing_slash_suffix URLs: 1 URLs, 51 requests
remaining URLs:   280 URLs, 1885 requests
--------------------------------------------------------------------------------
adobe_coldfusion: CFIDE/
adobe_coldfusion_suffix URLs: 20 URLs, 136 requests
remaining URLs:   260 URLs, 1749 requests
--------------------------------------------------------------------------------
websphere: IBMWebAS|webapp|WebSphere|SmarTicketApp|estore
websphere_suffix URLs: 18 URLs, 149 requests
remaining URLs:   242 URLs, 1600 requests
--------------------------------------------------------------------------------
iis: IISSamples|iisadmin|iisadmpwd|iisstart|msadc|/samples/(?:dbsamp|gbook|htmlsamp|isapi|sampsite)/
iis_suffix URLs: 58 URLs, 393 requests
remaining URLs:   184 URLs, 1207 requests
--------------------------------------------------------------------------------
frontpage: _cti|_private|_vti|postinfo\.html
frontpage_suffix URLs: 24 URLs, 186 requests
remaining URLs:   160 URLs, 1021 requests
--------------------------------------------------------------------------------
java: WEB-INF|\.do$|flash/java/javabean|FlashJavaBean|jstl-war
java_suffix URLs: 7 URLs, 50 requests
remaining URLs:   153 URLs, 971 requests
--------------------------------------------------------------------------------
lotus_domino: \.nsf$|/mail\.box$
lotus_domino_suffix URLs: 19 URLs, 134 requests
remaining URLs:   134 URLs, 837 requests
--------------------------------------------------------------------------------
asf: asf-logo-wide
asf_suffix URLs: 72 URLs, 529 requests
remaining URLs:   62 URLs, 308 requests
--------------------------------------------------------------------------------
portal_app: e2ePortalProject
portal_app_suffix URLs: 1 URLs, 4 requests
remaining URLs:   61 URLs, 304 requests
--------------------------------------------------------------------------------
file: databasenotes\.html
file_suffix URLs: 1 URLs, 4 requests
remaining URLs:   60 URLs, 300 requests
--------------------------------------------------------------------------------

In [23]:
print(f"Dataframe shape: {anom_only_remaining_df.shape}")
print(f"pattern_families:\n{json.dumps(pattern_families, indent=2)}")

Dataframe shape: (60, 2)
pattern_families:
{
  "extensions": [
    "\\.(?:bak|old|inc|java|jsp)"
  ],
  "numeric-id": [
    "\\d{10,}"
  ],
  "trailing_slash": [
    "^https?://[^/:]+:\\d{1,5}/$"
  ],
  "adobe_coldfusion": [
    "CFIDE/"
  ],
  "websphere": [
    "IBMWebAS",
    "webapp|WebSphere|SmarTicketApp",
    "estore"
  ],
  "iis": [
    "IISSamples",
    "iisadmin|iisadmpwd",
    "iisstart|msadc",
    "/samples/(?:dbsamp|gbook|htmlsamp|isapi|sampsite)/"
  ],
  "frontpage": [
    "_cti|_private|_vti",
    "postinfo\\.html"
  ],
  "java": [
    "WEB-INF",
    "\\.do$|flash/java/javabean|FlashJavaBean",
    "jstl-war"
  ],
  "lotus_domino": [
    "\\.nsf$",
    "/mail\\.box$"
  ],
  "asf": [
    "asf-logo-wide"
  ],
  "portal_app": [
    "e2ePortalProject"
  ],
  "file": [
    "databasenotes\\.html"
  ]
}

---

Sample next batch of URLs for analysis from the filtered dataset

In [24]:
anom_only_remaining_df.head(30)

label                                               anom  norm
url
http://localhost:8080/scripts/tools/drvrs.exe         14     0
http://localhost:8080/scripts/tools/dsnform.exe        4     0
http://localhost:8080/scripts/tools/mkilog.exe         9     0
http://localhost:8080/scripts/tools/newdsn.exe         7     0
http://localhost:8080/servlet/ErrorReporter            5     0
http://localhost:8080/servlet/HelloWorldServlet        8     0
http://localhost:8080/servlet/SimpleServlet            8     0
http://localhost:8080/servlet/SnoopServlet             9     0
http://localhost:8080/servlet/aphtpassword             5     0
http://localhost:8080/servlet/hello                    8     0
http://localhost:8080/servlet/snoop                    6     0
http://localhost:8080/servlet/snoop2                   5     0
http://localhost:8080/techniques/servlets/index...    14     0
http://localhost:8080/theme                            9     0
http://localhost:8080/tienda1/global/                  4     0
http://localhost:8080/tienda1/global/estilos.css/      4     0
http://localhost:8080/tienda1/global/estilos.css~      4     0
http://localhost:8080/tienda1/global/~                 1     0
http://localhost:8080/tienda1/global~                  5     0
http://localhost:8080/tienda1/imagenes/                5     0
http://localhost:8080/tienda1/imagenes/1.gif/          6     0
http://localhost:8080/tienda1/imagenes/1.gif/~         1     0
http://localhost:8080/tienda1/imagenes/1.gif~          1     0
http://localhost:8080/tienda1/imagenes/2.gif/          6     0
http://localhost:8080/tienda1/imagenes/2.gif/~         1     0
http://localhost:8080/tienda1/imagenes/2.gif~          2     0
http://localhost:8080/tienda1/imagenes/3.gif/          8     0
http://localhost:8080/tienda1/imagenes/3.gif/~         1     0
http://localhost:8080/tienda1/imagenes/3.gif~          2     0
http://localhost:8080/tienda1/imagenes/cmenbul....     1     0

**Observations:**  

Multiple Malformed URLs variations: 
- More variations of IIS scan probes - URLs with (`/scripts/tools...`)
- More variations of Java metadata probes - URLs with `servlet...`)
- More variations of websphere probes - URLs with `techniques/servlets...`)
- Wordlist (generic bait) probe - URLs with (`theme`)
- Editor backup file suffix `~` *(emacs/vi convention)* - URLs with (`tienda1/...~`)
- URL ends with trailing slash - change earlier defined `trailing_slash_pattern` `(r"^https?://[^/:]+:\d{1,5}/$")` to cover for URLs api/endpoint/paths/ that ends with `/`

In [26]:
# Define the patterns
more_iis_patterns = (r"/scripts/tools/.*\.exe")
more_java_patterns = (r"/servlet/(?:Snoop|Hello|Simple|snoop2?|ErrorReporter|aphtpassword|hello)")
more_websphere_patterns = (r"techniques/servlets")
#known_scanner_bait_pattern = (r"^http://localhost:8080/theme$")
known_scanner_bait_pattern = (r"^https?://[^/:]+:\d{1,5}/theme$")
tilde_backup_file_pattern = (r"~$|~/|/~$")
overwrite_trailing_slash_pattern = (r"^https?://[^/:]+:\d{1,5}.*/$")

# Add more IIS family patterns
extend_pattern("iis", more_iis_patterns)

# Add more Java family patterns
extend_pattern("java", more_java_patterns)

# Add more websphere family patterns
extend_pattern("websphere", more_websphere_patterns)

# Add new scanner bait family and add patterns
new_pattern_family("known_scanner_bait")
extend_pattern("known_scanner_bait", known_scanner_bait_pattern)

# Add new tilde family and add patterns
new_pattern_family("tilde_backup_file")
extend_pattern("tilde_backup_file", tilde_backup_file_pattern)

# Overwrite trailing slash family and add patterns
overwrite_pattern("trailing_slash", overwrite_trailing_slash_pattern)

# Compile the pattern
compiled = compiled_pattern(pattern_families)

# Reset to original Dataset
anom_only_remaining_df = anom_only_urls_df
print(anom_only_remaining_df.shape)

# Filter URLs on compiled patterns
anom_only_remaining_df = filter_urls(anom_only_remaining_df, compiled)

compiled_pattern: {'extensions': '\\.(?:bak|old|inc|java|jsp)', 'numeric-id': '\\d{10,}', 'trailing_slash': '^https?://[^/:]+:\\d{1,5}.*/$', 'adobe_coldfusion': 'CFIDE/', 'websphere': 'IBMWebAS|webapp|WebSphere|SmarTicketApp|estore|techniques/servlets|techniques/servlets', 'iis': 'IISSamples|iisadmin|iisadmpwd|iisstart|msadc|/samples/(?:dbsamp|gbook|htmlsamp|isapi|sampsite)/|/scripts/tools/.*\\.exe|/scripts/tools/.*\\.exe', 'frontpage': '_cti|_private|_vti|postinfo\\.html', 'java': 'WEB-INF|\\.do$|flash/java/javabean|FlashJavaBean|jstl-war|/servlet/(?:Snoop|Hello|Simple|snoop2?|ErrorReporter|aphtpassword|hello)|/servlet/(?:Snoop|Hello|Simple|snoop2?|ErrorReporter|aphtpassword|hello)', 'lotus_domino': '\\.nsf$|/mail\\.box$', 'asf': 'asf-logo-wide', 'portal_app': 'e2ePortalProject', 'file': 'databasenotes\\.html', 'known_scanner_bait': '^https?://[^/:]+:\\d{1,5}/theme$', 'tilde_backup_file': '~$|~/|/~$'}
(1615, 2)
extensions: \.(?:bak|old|inc|java|jsp)
extensions_suffix URLs: 1308 URLs, 3398 requests
remaining URLs:   307 URLs, 2110 requests
--------------------------------------------------------------------------------
numeric-id: \d{10,}
numeric-id_suffix URLs: 26 URLs, 174 requests
remaining URLs:   281 URLs, 1936 requests
--------------------------------------------------------------------------------
trailing_slash: ^https?://[^/:]+:\d{1,5}.*/$
trailing_slash_suffix URLs: 41 URLs, 402 requests
remaining URLs:   240 URLs, 1534 requests
--------------------------------------------------------------------------------
adobe_coldfusion: CFIDE/
adobe_coldfusion_suffix URLs: 20 URLs, 136 requests
remaining URLs:   220 URLs, 1398 requests
--------------------------------------------------------------------------------
websphere: IBMWebAS|webapp|WebSphere|SmarTicketApp|estore|techniques/servlets|techniques/servlets
websphere_suffix URLs: 18 URLs, 140 requests
remaining URLs:   202 URLs, 1258 requests
--------------------------------------------------------------------------------
iis: IISSamples|iisadmin|iisadmpwd|iisstart|msadc|/samples/(?:dbsamp|gbook|htmlsamp|isapi|sampsite)/|/scripts/tools/.*\.exe|/scripts/tools/.*\.exe
iis_suffix URLs: 62 URLs, 427 requests
remaining URLs:   140 URLs, 831 requests
--------------------------------------------------------------------------------
frontpage: _cti|_private|_vti|postinfo\.html
frontpage_suffix URLs: 17 URLs, 104 requests
remaining URLs:   123 URLs, 727 requests
--------------------------------------------------------------------------------
java: WEB-INF|\.do$|flash/java/javabean|FlashJavaBean|jstl-war|/servlet/(?:Snoop|Hello|Simple|snoop2?|ErrorReporter|aphtpassword|hello)|/servlet/(?:Snoop|Hello|Simple|snoop2?|ErrorReporter|aphtpassword|hello)
java_suffix URLs: 15 URLs, 104 requests
remaining URLs:   108 URLs, 623 requests
--------------------------------------------------------------------------------
lotus_domino: \.nsf$|/mail\.box$
lotus_domino_suffix URLs: 19 URLs, 134 requests
remaining URLs:   89 URLs, 489 requests
--------------------------------------------------------------------------------
asf: asf-logo-wide
asf_suffix URLs: 55 URLs, 359 requests
remaining URLs:   34 URLs, 130 requests
--------------------------------------------------------------------------------
portal_app: e2ePortalProject
portal_app_suffix URLs: 1 URLs, 4 requests
remaining URLs:   33 URLs, 126 requests
--------------------------------------------------------------------------------
file: databasenotes\.html
file_suffix URLs: 1 URLs, 4 requests
remaining URLs:   32 URLs, 122 requests
--------------------------------------------------------------------------------
known_scanner_bait: ^https?://[^/:]+:\d{1,5}/theme$
known_scanner_bait_suffix URLs: 1 URLs, 9 requests
remaining URLs:   31 URLs, 113 requests
--------------------------------------------------------------------------------
tilde_backup_file: ~$|~/|/~$
tilde_backup_file_suffix URLs: 28 URLs, 99 requests
remaining URLs:   3 URLs, 14 requests
--------------------------------------------------------------------------------

In [27]:
print(f"Dataframe shape: {anom_only_remaining_df.shape}")
print(f"pattern_families:\n{json.dumps(pattern_families, indent=2)}")

Dataframe shape: (3, 2)
pattern_families:
{
  "extensions": [
    "\\.(?:bak|old|inc|java|jsp)"
  ],
  "numeric-id": [
    "\\d{10,}"
  ],
  "trailing_slash": [
    "^https?://[^/:]+:\\d{1,5}.*/$"
  ],
  "adobe_coldfusion": [
    "CFIDE/"
  ],
  "websphere": [
    "IBMWebAS",
    "webapp|WebSphere|SmarTicketApp",
    "estore",
    "techniques/servlets",
    "techniques/servlets"
  ],
  "iis": [
    "IISSamples",
    "iisadmin|iisadmpwd",
    "iisstart|msadc",
    "/samples/(?:dbsamp|gbook|htmlsamp|isapi|sampsite)/",
    "/scripts/tools/.*\\.exe",
    "/scripts/tools/.*\\.exe"
  ],
  "frontpage": [
    "_cti|_private|_vti",
    "postinfo\\.html"
  ],
  "java": [
    "WEB-INF",
    "\\.do$|flash/java/javabean|FlashJavaBean",
    "jstl-war",
    "/servlet/(?:Snoop|Hello|Simple|snoop2?|ErrorReporter|aphtpassword|hello)",
    "/servlet/(?:Snoop|Hello|Simple|snoop2?|ErrorReporter|aphtpassword|hello)"
  ],
  "lotus_domino": [
    "\\.nsf$",
    "/mail\\.box$"
  ],
  "asf": [
    "asf-logo-wide"
  ],
  "portal_app": [
    "e2ePortalProject"
  ],
  "file": [
    "databasenotes\\.html"
  ],
  "known_scanner_bait": [
    "^https?://[^/:]+:\\d{1,5}/theme$"
  ],
  "tilde_backup_file": [
    "~$|~/|/~$"
  ]
}

---

Sample next batch of URLs for analysis from the filtered dataset

In [28]:
anom_only_remaining_df.head(30)

label                                            anom  norm
url
http://localhost:8080/wliconsole                    5     0
http://localhost:8080/worldmusic/action/catalog     5     0
http://localhost:8080/worldmusic/action/cdlist      4     0

In [ ]:
**Observations:**  

Last few URL variations: 
- More variations of WebSphere scan probes - URLs with (`wliconsole`)
- More variations of Java probes - URLs with `worldmusic...`)

In [29]:
# Define the patterns
more_java_patterns = (r"wliconsole")
more_websphere_patterns = (r"worldmusic")

# Add more Java family patterns
extend_pattern("java", more_java_patterns)

# Add more websphere family patterns
extend_pattern("websphere", more_websphere_patterns)

# Compile the pattern
compiled = compiled_pattern(pattern_families)

# Reset to original Dataset
anom_only_remaining_df = anom_only_urls_df
print(anom_only_remaining_df.shape)

# Filter URLs on compiled patterns
anom_only_remaining_df = filter_urls(anom_only_remaining_df, compiled)

compiled_pattern: {'extensions': '\\.(?:bak|old|inc|java|jsp)', 'numeric-id': '\\d{10,}', 'trailing_slash': '^https?://[^/:]+:\\d{1,5}.*/$', 'adobe_coldfusion': 'CFIDE/', 'websphere': 'IBMWebAS|webapp|WebSphere|SmarTicketApp|estore|techniques/servlets|techniques/servlets|worldmusic', 'iis': 'IISSamples|iisadmin|iisadmpwd|iisstart|msadc|/samples/(?:dbsamp|gbook|htmlsamp|isapi|sampsite)/|/scripts/tools/.*\\.exe|/scripts/tools/.*\\.exe', 'frontpage': '_cti|_private|_vti|postinfo\\.html', 'java': 'WEB-INF|\\.do$|flash/java/javabean|FlashJavaBean|jstl-war|/servlet/(?:Snoop|Hello|Simple|snoop2?|ErrorReporter|aphtpassword|hello)|/servlet/(?:Snoop|Hello|Simple|snoop2?|ErrorReporter|aphtpassword|hello)|wliconsole', 'lotus_domino': '\\.nsf$|/mail\\.box$', 'asf': 'asf-logo-wide', 'portal_app': 'e2ePortalProject', 'file': 'databasenotes\\.html', 'known_scanner_bait': '^https?://[^/:]+:\\d{1,5}/theme$', 'tilde_backup_file': '~$|~/|/~$'}
(1615, 2)
extensions: \.(?:bak|old|inc|java|jsp)
extensions_suffix URLs: 1308 URLs, 3398 requests
remaining URLs:   307 URLs, 2110 requests
--------------------------------------------------------------------------------
numeric-id: \d{10,}
numeric-id_suffix URLs: 26 URLs, 174 requests
remaining URLs:   281 URLs, 1936 requests
--------------------------------------------------------------------------------
trailing_slash: ^https?://[^/:]+:\d{1,5}.*/$
trailing_slash_suffix URLs: 41 URLs, 402 requests
remaining URLs:   240 URLs, 1534 requests
--------------------------------------------------------------------------------
adobe_coldfusion: CFIDE/
adobe_coldfusion_suffix URLs: 20 URLs, 136 requests
remaining URLs:   220 URLs, 1398 requests
--------------------------------------------------------------------------------
websphere: IBMWebAS|webapp|WebSphere|SmarTicketApp|estore|techniques/servlets|techniques/servlets|worldmusic
websphere_suffix URLs: 20 URLs, 149 requests
remaining URLs:   200 URLs, 1249 requests
--------------------------------------------------------------------------------
iis: IISSamples|iisadmin|iisadmpwd|iisstart|msadc|/samples/(?:dbsamp|gbook|htmlsamp|isapi|sampsite)/|/scripts/tools/.*\.exe|/scripts/tools/.*\.exe
iis_suffix URLs: 62 URLs, 427 requests
remaining URLs:   138 URLs, 822 requests
--------------------------------------------------------------------------------
frontpage: _cti|_private|_vti|postinfo\.html
frontpage_suffix URLs: 17 URLs, 104 requests
remaining URLs:   121 URLs, 718 requests
--------------------------------------------------------------------------------
java: WEB-INF|\.do$|flash/java/javabean|FlashJavaBean|jstl-war|/servlet/(?:Snoop|Hello|Simple|snoop2?|ErrorReporter|aphtpassword|hello)|/servlet/(?:Snoop|Hello|Simple|snoop2?|ErrorReporter|aphtpassword|hello)|wliconsole
java_suffix URLs: 16 URLs, 109 requests
remaining URLs:   105 URLs, 609 requests
--------------------------------------------------------------------------------
lotus_domino: \.nsf$|/mail\.box$
lotus_domino_suffix URLs: 19 URLs, 134 requests
remaining URLs:   86 URLs, 475 requests
--------------------------------------------------------------------------------
asf: asf-logo-wide
asf_suffix URLs: 55 URLs, 359 requests
remaining URLs:   31 URLs, 116 requests
--------------------------------------------------------------------------------
portal_app: e2ePortalProject
portal_app_suffix URLs: 1 URLs, 4 requests
remaining URLs:   30 URLs, 112 requests
--------------------------------------------------------------------------------
file: databasenotes\.html
file_suffix URLs: 1 URLs, 4 requests
remaining URLs:   29 URLs, 108 requests
--------------------------------------------------------------------------------
known_scanner_bait: ^https?://[^/:]+:\d{1,5}/theme$
known_scanner_bait_suffix URLs: 1 URLs, 9 requests
remaining URLs:   28 URLs, 99 requests
--------------------------------------------------------------------------------
tilde_backup_file: ~$|~/|/~$
tilde_backup_file_suffix URLs: 28 URLs, 99 requests
remaining URLs:   0 URLs, 0 requests
--------------------------------------------------------------------------------

In [31]:
print(f"Dataframe shape: {anom_only_remaining_df.shape}")
print(f"pattern_families:\n{json.dumps(pattern_families, indent=2)}")

Dataframe shape: (0, 2)
pattern_families:
{
  "extensions": [
    "\\.(?:bak|old|inc|java|jsp)"
  ],
  "numeric-id": [
    "\\d{10,}"
  ],
  "trailing_slash": [
    "^https?://[^/:]+:\\d{1,5}.*/$"
  ],
  "adobe_coldfusion": [
    "CFIDE/"
  ],
  "websphere": [
    "IBMWebAS",
    "webapp|WebSphere|SmarTicketApp",
    "estore",
    "techniques/servlets",
    "techniques/servlets",
    "worldmusic"
  ],
  "iis": [
    "IISSamples",
    "iisadmin|iisadmpwd",
    "iisstart|msadc",
    "/samples/(?:dbsamp|gbook|htmlsamp|isapi|sampsite)/",
    "/scripts/tools/.*\\.exe",
    "/scripts/tools/.*\\.exe"
  ],
  "frontpage": [
    "_cti|_private|_vti",
    "postinfo\\.html"
  ],
  "java": [
    "WEB-INF",
    "\\.do$|flash/java/javabean|FlashJavaBean",
    "jstl-war",
    "/servlet/(?:Snoop|Hello|Simple|snoop2?|ErrorReporter|aphtpassword|hello)",
    "/servlet/(?:Snoop|Hello|Simple|snoop2?|ErrorReporter|aphtpassword|hello)",
    "wliconsole"
  ],
  "lotus_domino": [
    "\\.nsf$",
    "/mail\\.box$"
  ],
  "asf": [
    "asf-logo-wide"
  ],
  "portal_app": [
    "e2ePortalProject"
  ],
  "file": [
    "databasenotes\\.html"
  ],
  "known_scanner_bait": [
    "^https?://[^/:]+:\\d{1,5}/theme$"
  ],
  "tilde_backup_file": [
    "~$|~/|/~$"
  ]
}

The anomalous URLs are now fully bucketed into families. These can be used for feature engineering

---